# Generated by Django 4.2.8 on 2023-12-22 06:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_kyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='consumer_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kyc',
            name='pdf_file',
            field=models.FileField(upload_to='pdf_documents/'),
        ),
    ]
